import { NextRequest, NextResponse } from "next/server";
import { secretHash } from "@/lib/crypto";
import { serviceClient } from "@/lib/hospital";
export const runtime="nodejs";
type Arguments=Record<string,unknown>; const iso=(value:string)=>/^20\d{2}-\d{2}-\d{2}$/.test(value); const clean=(value:unknown)=>String(value??"").replace(/\D/g,"");
async function tool(hospitalId:string,name:string,args:Arguments) { const db=serviceClient();
 if(name==="listDoctors") { const {data,error}=await db.from("doctors").select("id,name,department").eq("hospital_id",hospitalId).eq("enabled",true).order("department").order("name"); if(error) throw error; return {doctors:data??[]}; }
 if(name==="getHospitalInfo") { const {data,error}=await db.from("hospital_settings").select("hospital_name,departments,opening_time,closing_time,emergency_number").eq("hospital_id",hospitalId).maybeSingle(); if(error) throw error; return data??{message:"Hospital information is not configured."}; }
 if(name==="getAvailableSlots") { const doctorId=String(args.doctorId??""); const date=String(args.date??""); if(!doctorId||!iso(date)) throw new Error("doctorId and a YYYY-MM-DD date are required."); const [{data:doctor,error:doctorError},{data:settings},{data:booked,error:bookedError}]=await Promise.all([db.from("doctors").select("id,name,department,working_days,start_time,end_time,consultation_duration").eq("hospital_id",hospitalId).eq("id",doctorId).eq("enabled",true).single(),db.from("hospital_settings").select("opening_time,closing_time,slot_duration").eq("hospital_id",hospitalId).maybeSingle(),db.from("appointments").select("appointment_time").eq("hospital_id",hospitalId).eq("doctor_id",doctorId).eq("appointment_date",date).eq("status","upcoming")]); if(doctorError||bookedError||!doctor) throw doctorError??bookedError??new Error("Doctor unavailable."); const weekday=new Intl.DateTimeFormat("en-US",{weekday:"long",timeZone:"UTC"}).format(new Date(`${date}T12:00:00Z`)); if(!doctor.working_days.includes(weekday)) return {slots:[],message:`${doctor.name} is not available on ${weekday}.`}; const toMinutes=(v:string)=>{const [h,m]=v.slice(0,5).split(":").map(Number);return h*60+m;}; const start=Math.max(toMinutes(doctor.start_time),toMinutes(settings?.opening_time??doctor.start_time)); const end=Math.min(toMinutes(doctor.end_time),toMinutes(settings?.closing_time??doctor.end_time)); const duration=doctor.consultation_duration||settings?.slot_duration||20; const busy=new Set((booked??[]).map(x=>String(x.appointment_time).slice(0,5))); const slots=Array.from({length:Math.max(0,Math.floor((end-start)/duration))},(_,i)=>{const n=start+i*duration;return `${String(Math.floor(n/60)).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`;}).filter(x=>!busy.has(x)).slice(0,8); return {doctor:{id:doctor.id,name:doctor.name,department:doctor.department},date,slots}; }
 if(name==="bookAppointment") { const patientName=String(args.patientName??"").trim(),phone=clean(args.phoneNumber),doctorId=String(args.doctorId??""),date=String(args.date??""),time=String(args.time??"").slice(0,5); if(!patientName||!phone||!doctorId||!iso(date)||!/^\d{2}:\d{2}$/.test(time)) throw new Error("Patient name, phone number, doctorId, YYYY-MM-DD date, and HH:MM time are required."); const [{data:doctor,error:doctorError},{data:patient,error:patientError}]=await Promise.all([db.from("doctors").select("id,name,department").eq("hospital_id",hospitalId).eq("id",doctorId).eq("enabled",true).single(),db.from("patients").upsert({hospital_id:hospitalId,phone_number:phone,full_name:patientName,last_seen:new Date().toISOString()},{onConflict:"hospital_id,phone_number"}).select("id").single()]); if(doctorError||patientError||!doctor||!patient) throw doctorError??patientError??new Error("Cannot create appointment."); const {data:existing}=await db.from("appointments").select("id").eq("hospital_id",hospitalId).eq("doctor_id",doctorId).eq("appointment_date",date).eq("appointment_time",time).eq("status","upcoming").maybeSingle(); if(existing) throw new Error("That slot is no longer available."); const {data,error}=await db.from("appointments").insert({hospital_id:hospitalId,patient_id:patient.id,patient_name:patientName,phone_number:phone,doctor_id:doctor.id,doctor_name:doctor.name,department:doctor.department,appointment_date:date,appointment_time:time}).select("id").single(); if(error) throw error; return {success:true,appointmentId:data?.id,confirmation:`Appointment confirmed with ${doctor.name} on ${date} at ${time}.`}; }
 if(name==="checkAppointmentStatus") { const phone=clean(args.phoneNumber); const {data,error}=await db.from("appointments").select("doctor_name,department,appointment_date,appointment_time,status").eq("hospital_id",hospitalId).eq("phone_number",phone).order("appointment_date",{ascending:false}).limit(3); if(error) throw error; return {appointments:data??[]}; }
 if(name==="cancelAppointment") { const id=String(args.appointmentId??""); const {error}=await db.from("appointments").update({status:"cancelled"}).eq("hospital_id",hospitalId).eq("id",id); if(error) throw error; return {success:true,message:"Appointment cancelled."}; }
 if(name==="rescheduleAppointment") { return {message:"Please first use cancelAppointment for the existing appointment, then check new slots and bookAppointment after the patient confirms."}; }
 throw new Error("Unknown tool."); }
export async function POST(request:NextRequest,{params}:{params:Promise<{hospitalId:string}>}) { const {hospitalId}=await params; console.log("Vapi webhook received",{hospitalId}); let message:Record<string,unknown>|undefined; try { const token=request.nextUrl.searchParams.get("token")??""; const db=serviceClient(); const {data:connection,error}=await db.from("vapi_connections").select("*").eq("hospital_id",hospitalId).maybeSingle(); if(error||!connection||!connection.enabled||secretHash(token)!==connection.webhook_secret_hash) return NextResponse.json({error:"Unauthorized"},{status:401}); const payload=await request.json() as {message?:Record<string,unknown>}; message=payload.message; const type=String(message?.type??""); if(type==="tool-calls") { const calls=(message?.toolCallList??[]) as Array<{id:string;name:string;arguments?:Arguments;parameters?:Arguments}>; const results=await Promise.all(calls.map(async call=>{try{return {toolCallId:call.id,name:call.name,result:JSON.stringify(await tool(hospitalId,call.name,call.arguments??call.parameters??{})).replace(/[\r\n]/g," ")};}catch(error){console.error("Vapi tool failed",{name:call.name,error});return {toolCallId:call.id,name:call.name,error:error instanceof Error?error.message:"Tool failed"};}})); return NextResponse.json({results}); }
 if(type==="end-of-call-report"||type==="status-update") { const call=(message?.call??{}) as Record<string,unknown>; const artifact=(message?.artifact??{}) as Record<string,unknown>; const customer=(message?.customer??call.customer??{}) as Record<string,unknown>; const started=String(message?.startedAt??call.startedAt??"")||null,ended=String(message?.endedAt??call.endedAt??"")||null; const duration=started&&ended?Math.max(0,Math.round((Date.parse(ended)-Date.parse(started))/1000)):null; const callId=String(call.id??""); if(callId) { const {error:logError}=await db.from("vapi_call_logs").upsert({hospital_id:hospitalId,vapi_call_id:callId,caller_phone:clean(customer.number) || null,transcript:String(artifact.transcript??""),duration_seconds:duration,status:type==="status-update"?String(message?.status??"in_progress"):"completed",failure_reason:type==="end-of-call-report"?String(message?.endedReason??"")||null:null,started_at:started,ended_at:ended},{onConflict:"hospital_id,vapi_call_id"}); if(logError) console.error("Vapi call log write failed",logError); } } return NextResponse.json({ok:true}); } catch(error) { console.error("Vapi webhook failed",{message,error}); return NextResponse.json({ok:true}); } }
