import { randomBytes } from "node:crypto";
import { NextRequest, NextResponse } from "next/server";
import { encrypt, secretHash } from "@/lib/crypto";
import { ensureHospital, serviceClient } from "@/lib/hospital";
import { createClient } from "@/lib/supabase/server";
export const runtime = "nodejs";
async function hospital() { const auth = await createClient(); const { data:{ user } } = await auth.auth.getUser(); if (!user) throw new Error("Unauthorized"); return ensureHospital(user.id); }
export async function GET() { try { const hospitalId=await hospital(); const {data,error}=await serviceClient().from("vapi_connections").select("assistant_id,phone_number_id,default_language,greeting,enabled,updated_at").eq("hospital_id",hospitalId).maybeSingle(); if(error) throw error; return NextResponse.json({connection:data,hospitalId}); } catch(error) { return NextResponse.json({error:error instanceof Error?error.message:"Unable to load Vapi settings."},{status:401}); } }
export async function POST(request:NextRequest) { try { const hospitalId=await hospital(); const body=await request.json() as {apiKey?:string;assistantId?:string;phoneNumberId?:string;defaultLanguage?:string;greeting?:string;enabled?:boolean}; if(!body.apiKey?.trim()||!body.assistantId?.trim()) return NextResponse.json({error:"Vapi API key and Assistant ID are required."},{status:400}); const secret=randomBytes(32).toString("base64url"); const {error}=await serviceClient().from("vapi_connections").upsert({hospital_id:hospitalId,api_key_encrypted:encrypt(body.apiKey.trim()),assistant_id:body.assistantId.trim(),phone_number_id:body.phoneNumberId?.trim()||null,default_language:body.defaultLanguage||"Marathi",greeting:body.greeting?.trim()||null,enabled:body.enabled!==false,webhook_secret_hash:secretHash(secret),updated_at:new Date().toISOString()},{onConflict:"hospital_id"}); if(error) throw error; const origin=process.env.NEXT_PUBLIC_APP_URL??request.nextUrl.origin; return NextResponse.json({ok:true,serverUrl:`${origin}/api/vapi/webhook/${hospitalId}?token=${secret}`}); } catch(error) { console.error("Vapi connection setup failed",error); return NextResponse.json({error:error instanceof Error?error.message:"Unable to save Vapi settings."},{status:500}); } }
