import { NextRequest, NextResponse } from "next/server";
import { hospitalForChannel, requireN8n } from "@/lib/n8n";
import { serviceClient } from "@/lib/hospital";

export const runtime = "nodejs";

/** Stores the reply generated by n8n so the live dashboard has the complete chat. */
export async function POST(request: NextRequest) {
  const denied = requireN8n(request); if (denied) return denied;
  try {
    const body = await request.json() as { phoneNumberId?: string; instanceName?: string; patientPhone?: string; message?: string };
    const phoneNumberId = body.phoneNumberId?.trim() ?? "";
    const instanceName = body.instanceName?.trim() ?? "";
    const patientPhone = body.patientPhone?.replace(/\D/g, "") ?? "";
    const message = body.message?.trim() ?? "";
    if ((!/^\d+$/.test(phoneNumberId) && !instanceName) || !/^\d{8,15}$/.test(patientPhone) || !message) {
      return NextResponse.json({ error: "A valid channel, patient phone, and assistant message are required." }, { status: 400 });
    }

    const hospitalId = await hospitalForChannel({ phoneNumberId, instanceName });
    const db = serviceClient();
    const now = new Date().toISOString();
    const { data: conversation, error: conversationError } = await db
      .from("conversations")
      .upsert({ hospital_id: hospitalId, phone_number: patientPhone, updated_at: now }, { onConflict: "hospital_id,phone_number" })
      .select("id")
      .single();
    if (conversationError || !conversation) throw conversationError ?? new Error("Could not create patient conversation.");

    const { error: messageError } = await db.from("messages").insert({ conversation_id: conversation.id, role: "assistant", content: message });
    if (messageError) throw messageError;
    return NextResponse.json({ ok: true, conversationId: conversation.id });
  } catch (error) {
    console.error("n8n assistant message save failed", error);
    return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to save assistant message." }, { status: 500 });
  }
}
