"use client";

import { FormEvent, useEffect, useState } from "react";

type Connection = { provider: "groq" | "openai"; model: string; enabled: boolean; updated_at: string } | null;

export default function AiSettings() {
  const [connection, setConnection] = useState<Connection>(null); const [provider, setProvider] = useState<"groq" | "openai">("groq"); const [model, setModel] = useState("llama-3.3-70b-versatile"); const [apiKey, setApiKey] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { fetch("/api/ai-connection").then(async response => { const body = await response.json() as { connection?: Connection; error?: string }; if (!response.ok) { setMessage("AI settings need the Supabase ai-migration.sql file before they can be saved."); return; } if (body.connection) { setConnection(body.connection); setProvider(body.connection.provider); setModel(body.connection.model); } }).catch(() => setMessage("Unable to load AI settings.")); }, []);
  function providerChanged(value: "groq" | "openai") { setProvider(value); setModel(value === "groq" ? "llama-3.3-70b-versatile" : "gpt-4o-mini"); }
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); const response = await fetch("/api/ai-connection", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ provider, model, apiKey, enabled: true }) }); const body = await response.json() as { connection?: Connection; error?: string }; setBusy(false); if (!response.ok || !body.connection) { setMessage(body.error ?? "Unable to save AI settings."); return; } setConnection(body.connection); setApiKey(""); setMessage("AI receptionist settings saved."); }
  return <main className="shell"><section className="connection-card" style={{ width: "min(100%,760px)" }}><div className="brand">AI RECEPTIONIST</div><h1>Configure patient chat intelligence</h1><p>Use Groq or OpenAI for rich hospital FAQs and natural patient questions. Appointment booking, live slots, and confirmations remain protected by the dashboard rules.</p><div className={`connection-status ${connection?.enabled ? "connected" : "disconnected"}`}><b>{connection?.enabled ? `${connection.provider.toUpperCase()} connected` : "Using environment fallback"}</b><span>{connection?.model ?? "Configure a provider for this hospital"}</span></div><form onSubmit={save}><label className="field">AI provider<select value={provider} onChange={event => providerChanged(event.target.value as "groq" | "openai")}><option value="groq">Groq</option><option value="openai">OpenAI / ChatGPT</option></select></label><label className="field">Model<input value={model} onChange={event => setModel(event.target.value)} required /></label><label className="field">API key<input type="password" value={apiKey} onChange={event => setApiKey(event.target.value)} placeholder={connection ? "Enter only to replace the saved key" : "Paste the server API key"} required={!connection} /></label><p className="note">Keys are encrypted on the server and never returned to the browser. Groq recommended model: llama-3.3-70b-versatile. OpenAI recommended model: gpt-4o-mini.</p>{message && <p className={message.includes("saved") ? "success" : "error"}>{message}</p>}<button className="primary" disabled={busy}>{busy ? "Saving…" : "Save AI receptionist"}</button></form><a className="back-link" href="/dashboard">← Back to hospital dashboard</a></section></main>;
}
