"use client";
import { useEffect, useState } from "react";

type Connection = { instance_name: string; display_phone_number: string | null; status: "connected" | "disconnected" | "qr_pending"; last_error: string | null; updated_at: string };

export default function EvolutionConnection() {
  const [connection, setConnection] = useState<Connection | null>(null); const [serverUrl, setServerUrl] = useState(""); const [apiKey, setApiKey] = useState(""); const [instanceName, setInstanceName] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function refresh() { const response = await fetch("/api/evolution/connection"); if (response.ok) { const body = await response.json(); setConnection(body.connection); if (body.connection) setInstanceName(body.connection.instance_name); } }
  useEffect(() => { void refresh(); }, []);
  async function save(event: React.FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); const response = await fetch("/api/evolution/connection", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ serverUrl, apiKey, instanceName }) }); const body = await response.json(); setBusy(false); if (!response.ok) { setMessage(body.error ?? "Unable to connect Evolution API."); return; } setApiKey(""); setMessage(`Saved. Evolution instance status: ${body.status}.`); await refresh(); }
  async function checkStatus() { setBusy(true); setMessage(""); const response = await fetch("/api/evolution/connection", { method: "PATCH" }); const body = await response.json(); setBusy(false); setMessage(response.ok ? `Evolution instance status: ${body.status}.` : (body.error ?? "Status check failed.")); await refresh(); }
  return <main className="shell"><section className="connection-card"><div className="brand">Hospital WhatsApp</div><h1>Connect Evolution API</h1><p>Evolution receives and sends WhatsApp messages. n8n will run Gemini and appointment booking. Credentials are encrypted before storage.</p>{connection && <div className={`connection-status ${connection.status === "connected" ? "connected" : "disconnected"}`}><b>{connection.status === "qr_pending" ? "QR Pending" : connection.status === "connected" ? "Connected" : "Disconnected"}</b><span>{connection.display_phone_number || connection.instance_name}</span></div>}<form onSubmit={save}><label className="field">Evolution API server URL<input required type="url" value={serverUrl} onChange={(event) => setServerUrl(event.target.value)} placeholder="https://your-evolution-server.com" /></label><label className="field">Evolution API key<input required type="password" value={apiKey} onChange={(event) => setApiKey(event.target.value)} placeholder="Evolution global API key" /></label><label className="field">Instance name<input required value={instanceName} onChange={(event) => setInstanceName(event.target.value)} placeholder="hospital_whatsapp" /></label>{message && <p className="error">{message}</p>}<div style={{ display: "flex", gap: 10 }}><button className="primary" disabled={busy}>{busy ? "Working…" : "Save & test Evolution"}</button>{connection && <button type="button" className="secondary" disabled={busy} onClick={checkStatus}>Check status</button>}</div></form><section className="qr"><h2>Next: connect Evolution to n8n</h2><ol><li>Make sure the Evolution instance shows <b>Connected</b> after scanning its QR code.</li><li>Import the Evolution n8n workflow from this project.</li><li>In Evolution → Webhook, paste the n8n Webhook production URL and enable <b>MESSAGES_UPSERT</b>.</li></ol></section><a className="back-link" href="/dashboard">← Back to hospital dashboard</a></section></main>;
}
