import Link from "next/link";
import styles from "./creatoros.module.css";

const plans = [
  { name: "Basic", price: "₹5,000", text: "A polished WhatsApp booking agent and live appointment dashboard.", items: ["WhatsApp appointment booking", "Doctor & department selection", "Live dashboard", "Patient chat history"] },
  { name: "Standard", price: "₹7,000", text: "WhatsApp plus an AI voice receptionist for your hospital.", items: ["Everything in Basic", "AI Voice Receptionist", "Call logs & transcripts", "Marathi, Hindi & English"] },
  { name: "Pro", price: "₹10,000", text: "A tailored patient-engagement operating system for growing teams.", items: ["Everything in Standard", "Custom workflows", "Appointment reminders", "Priority setup & support"] },
];

export default function Home() {
  return <main className={styles.site}>
    <div className={styles.orbOne} /><div className={styles.orbTwo} /><div className={styles.grid} />
    <nav className={styles.nav}><Link href="/" className={styles.logo}><i>✦</i> Creator<span>OS</span></Link><div><a href="#plans">Plans</a><a href="#contact">Contact</a><Link className={styles.login} href="/login">Client login</Link></div></nav>
    <section className={styles.hero}>
      <div><p className={styles.kicker}>INTELLIGENT HOSPITAL OPERATIONS</p><h1>Care moves faster with <em>AI.</em></h1><p className={styles.lead}>CreatorOS builds a calm, always-on digital front desk—WhatsApp, voice calls, real appointment slots, and one beautiful dashboard.</p><div className={styles.actions}><Link className={styles.primary} href="/enquire?type=consultation">Build my agent <span>→</span></Link><a className={styles.secondary} href="#plans">Explore plans</a></div><p className={styles.note}>Designed for modern hospitals · Multilingual by default</p></div>
      <aside className={styles.heroCard}><div className={styles.cardTop}><span className={styles.pulse} /> <b>Reception is live</b><small>NOW</small></div><div className={styles.chatBubble}>नमस्कार! तुमची अपॉइंटमेंट बुक करू का?</div><div className={styles.chatBubbleAlt}>Yes, I need a doctor today.</div><div className={styles.aiLine}><i>✦</i> Checking live doctor slots…</div><div className={styles.flow}><span>Patient</span><b>→</b><span>AI agent</span><b>→</b><span>Booked</span></div></aside>
    </section>
    <section className={styles.features}><article><div className={styles.icon}>⌁</div><p className={styles.featureNumber}>01</p><h2>WhatsApp Agent</h2><p>A thoughtful receptionist for appointment questions, confirmations, and booking.</p></article><article><div className={styles.icon}>◉</div><p className={styles.featureNumber}>02</p><h2>Voice Agent</h2><p>Patients call naturally or use keypad choices to reserve a genuine live slot.</p></article><article><div className={styles.icon}>▦</div><p className={styles.featureNumber}>03</p><h2>Command Centre</h2><p>See doctors, patients, chats, appointments, calls, and statuses in one place.</p></article></section>
    <section id="plans" className={styles.pricing}><div><p className={styles.kicker}>CLEAR, SIMPLE PRICING</p><h2>Choose your care automation.</h2></div><div className={styles.planGrid}>{plans.map((plan) => <article className={plan.name === "Standard" ? styles.featured : ""} key={plan.name}>{plan.name === "Standard" && <small>Best value</small>}<p className={styles.planName}>{plan.name}</p><strong>{plan.price}</strong><p>{plan.text}</p><ul>{plan.items.map((item) => <li key={item}><i>✓</i>{item}</li>)}</ul><Link href={`/enquire?plan=${plan.name}`}>Get started <span>→</span></Link></article>)}</div></section>
    <section id="contact" className={styles.contact}><div><p className={styles.kicker}>LET&apos;S DESIGN THE RIGHT SYSTEM</p><h2>Your front desk, reimagined.</h2><p>Tell us about your hospital, staff hours, and patient languages. We will map the right automation together.</p></div><div className={styles.contactLinks}><a href="tel:+919420857650"><i>☎</i> +91 94208 57650</a><a href="mailto:knachiket081@gmail.com"><i>✉</i> knachiket081@gmail.com</a><Link className={styles.contactButton} href="/enquire?type=consultation">Start a conversation →</Link></div></section>
    <footer><span>© {new Date().getFullYear()} CreatorOS</span><a href="#terms">Terms & Conditions</a></footer><section id="terms" className={styles.terms}><h2>Terms &amp; Conditions</h2><p>CreatorOS provides software automation services. Hospital staff remain responsible for doctor schedules, patient information, medical decisions, emergency care, and final appointment verification. AI agents do not provide diagnosis, prescriptions, or emergency medical advice. Client data is processed only to provide the requested automation services. Prices cover setup unless a separate support or integration agreement is provided.</p></section>
  </main>;
}
