import Link from "next/link";
import styles from "./creatoros.module.css";
import pricing from "./pricing.module.css";

const setupPlans = [
  { name: "WhatsApp Appointment Automation", price: "₹10,000", text: "One-time setup charge for a complete WhatsApp appointment-booking system.", items: ["WhatsApp Cloud API connection", "English-first AI receptionist with Hindi & Marathi switching", "Live doctor, department and slot booking", "Hospital dashboard, staff handover and launch support"], cta: "Get WhatsApp Automation" },
  { name: "WhatsApp + AI Voice Agent Automation", price: "₹20,000", text: "One-time setup charge for a unified WhatsApp and voice appointment system.", items: ["Everything in WhatsApp Automation", "AI voice receptionist integration", "Shared doctors, patient records and appointment calendar", "Call flow, testing, go-live and team training"], cta: "Get Complete Automation", featured: true },
];
const maintenancePlans = [
  { name: "WhatsApp Care", price: "₹5,000 / month", text: "Maintenance and support for WhatsApp appointment automation.", items: ["Up to 150 patient conversations / month", "Monitoring, updates and support", "Dashboard and appointment workflow maintenance"] },
  { name: "Connected Reception", price: "₹7,000 / month", text: "Maintenance for WhatsApp + AI voice automation.", items: ["Up to 300 conversations / month", "Voice-agent workflow monitoring", "Priority support and monthly optimisation"], featured: true },
  { name: "Hospital Scale", price: "₹10,000 / month", text: "For busy hospitals that need a reliable automation partner.", items: ["Higher conversation/voice usage band", "Custom business-process automations", "Priority response, reporting and optimisation"] },
];
const demoWhatsApp = "https://wa.me/917378857650?text=Hello%20CreatorOS%2C%20I%20want%20to%20try%20the%20hospital%20appointment%20automation.";

export default function Home() {
  return <main className={styles.site}>
    <div className={styles.orbOne} /><div className={styles.orbTwo} /><div className={styles.grid} />
    <nav className={styles.nav}><Link href="/" className={styles.logo}><i>✦</i> Creater<span>OS</span><small>Hospital automation studio</small></Link><div><a href="#how-it-works">How it works</a><a href="#plans">Automation services</a><a href="#contact">Contact</a><Link className={styles.login} href="/login">Client login</Link></div></nav>
    <section className={styles.hero}>
      <div><p className={styles.kicker}>CREATEROS · AI AUTOMATION FOR HOSPITALS</p><h1>Your hospital&apos;s front desk, <em>automated.</em></h1><p className={styles.lead}>CreaterOS designs, integrates, and maintains practical hospital automation: WhatsApp receptionists, AI voice agents, real appointment slots, and a secure operations dashboard—built around how your team already works.</p><div className={styles.actions}><a className={styles.primary} href={demoWhatsApp} target="_blank" rel="noreferrer">Try our automation <span>→</span></a><Link className={styles.secondary} href="/enquire?type=consultation">Book a demo appointment</Link></div><p className={styles.note}>Demo & automation test: WhatsApp or call +91 73788 57650 · English by default, Hindi & Marathi available</p></div>
      <aside className={styles.heroCard}><div className={styles.cardTop}><span className={styles.pulse} /> <b>AI reception is live</b><small>24 / 7</small></div><div className={styles.chatBubble}>Hello! I can help you book an appointment. Which doctor or department do you need?</div><div className={styles.chatBubbleAlt}>I need a cardiologist tomorrow.</div><div className={styles.aiLine}><i>✦</i> Checking real-time doctor availability…</div><div className={styles.flow}><span>Patient</span><b>→</b><span>CreaterOS AI</span><b>→</b><span>Appointment booked</span></div></aside>
    </section>
    <section id="how-it-works" className={styles.features}><article><div className={styles.icon}>◌</div><p className={styles.featureNumber}>01</p><h2>Patient contacts you</h2><p>Patients message WhatsApp or call your hospital in English, Hindi, or Marathi.</p></article><article><div className={styles.icon}>✦</div><p className={styles.featureNumber}>02</p><h2>AI handles the conversation</h2><p>It answers routine hospital queries, gathers booking details, and checks only genuine available slots.</p></article><article><div className={styles.icon}>▦</div><p className={styles.featureNumber}>03</p><h2>Your team stays in control</h2><p>Appointments, patient details, doctor availability, chats, and calls stay in one hospital dashboard.</p></article></section>
    <section id="plans" className={styles.pricing}><div><p className={styles.kicker}>AUTOMATION SERVICES, NOT GENERIC SOFTWARE</p><h2>First we build your automation. Then we keep it performing.</h2><p>One-time setup covers implementation and integration. Maintenance is an ongoing service, scaled to patient conversations and voice usage.</p></div><div className={pricing.pricingLabel}>ONE-TIME SETUP & INTEGRATION</div><div className={styles.planGrid}>{setupPlans.map((plan) => <article className={plan.featured ? styles.featured : ""} key={plan.name}>{plan.featured && <small>Complete front desk</small>}<p className={styles.planName}>One-time setup</p><h3>{plan.name}</h3><strong>{plan.price}</strong><p>{plan.text}</p><ul>{plan.items.map((item) => <li key={item}><i>✓</i>{item}</li>)}</ul><Link href={`/enquire?plan=${encodeURIComponent(plan.name)}`}>{plan.cta} <span>→</span></Link></article>)}</div><div className={`${pricing.pricingLabel} ${pricing.maintenanceLabel}`}>ONGOING MAINTENANCE & USAGE-BASED SUPPORT</div><div className={styles.planGrid}>{maintenancePlans.map((plan) => <article className={plan.featured ? styles.featured : ""} key={plan.name}>{plan.featured && <small>Most chosen</small>}<p className={styles.planName}>Maintenance plan</p><h3>{plan.name}</h3><strong>{plan.price}</strong><p>{plan.text}</p><ul>{plan.items.map((item) => <li key={item}><i>✓</i>{item}</li>)}</ul><Link href={`/enquire?plan=${encodeURIComponent(`${plan.name} maintenance`)}`}>Discuss maintenance <span>→</span></Link></article>)}</div></section>
    <section id="contact" className={styles.contact}><div><p className={styles.kicker}>LET&apos;S BUILD YOUR AUTOMATION</p><h2>Give your team a reliable AI receptionist.</h2><p>We map hospital timings, doctors, appointment rules, language needs, WhatsApp, voice, and the dashboard into one practical service.</p></div><div className={styles.contactLinks}><a href={demoWhatsApp} target="_blank" rel="noreferrer"><i>◉</i> Try WhatsApp automation</a><a href="tel:+917378857650"><i>☎</i> Call +91 73788 57650</a><a href="mailto:knachiket081@gmail.com"><i>✉</i> knachiket081@gmail.com</a><Link className={styles.contactButton} href="/enquire?type=consultation">Get automation for your business →</Link></div></section>
    <footer><span>© {new Date().getFullYear()} CreaterOS</span><a href="#terms">Terms & Conditions</a></footer><section id="terms" className={styles.terms}><h2>Terms &amp; Conditions</h2><p>CreaterOS provides AI automation and integration services. One-time setup charges cover the scoped implementation. Monthly maintenance charges cover support, monitoring, improvements, and the included conversation or voice-usage band; additional usage or integrations may be quoted separately. Hospital staff remain responsible for schedules, patient information, medical decisions, emergency care, and final appointment verification. AI agents do not diagnose, prescribe, or provide emergency medical advice.</p></section>
  </main>;
}
