"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import type { Appointment, Conversation, Doctor, HospitalSettings, Message, Patient } from "@/lib/database.types";

type View = "Dashboard" | "Appointments" | "Doctors" | "Patients" | "WhatsApp Chats" | "Calendar" | "Hospital Settings" | "WhatsApp Connection";
const nav: View[] = ["Dashboard", "Appointments", "Doctors", "Patients", "WhatsApp Chats", "Calendar", "WhatsApp Connection", "Hospital Settings"];
const time = (t: string) => { const [h, m] = t.slice(0, 5).split(":").map(Number); return `${((h + 11) % 12) + 1}:${String(m).padStart(2,"0")} ${h >= 12 ? "PM" : "AM"}`; };
export default function DashboardClient({ hospitalId, initialConversations, initialMessages, initialAppointments, initialDoctors, initialPatients, initialSettings }: { hospitalId: string; initialConversations: Conversation[]; initialMessages: Message[]; initialAppointments: Appointment[]; initialDoctors: Doctor[]; initialPatients: Patient[]; initialSettings: HospitalSettings | null }) {
 const router = useRouter(); const [view,setView]=useState<View>("Dashboard"); const [conversations,setConversations]=useState(initialConversations); const [messages,setMessages]=useState(initialMessages); const [appointments,setAppointments]=useState(initialAppointments); const [doctors,setDoctors]=useState(initialDoctors); const [patients,setPatients]=useState(initialPatients); const [settings,setSettings]=useState(initialSettings); const [dark,setDark]=useState(true); const [selected,setSelected]=useState(initialConversations[0]?.id||""); const [query,setQuery]=useState(""); const selectedConversation=conversations.find(x=>x.id===selected); const thread=useMemo(()=>messages.filter(x=>x.conversation_id===selected),[messages,selected]); const today=new Date().toISOString().slice(0,10); const active=appointments.filter(x=>x.status==="upcoming");
 useEffect(()=>{setAppointments(initialAppointments);setPatients(initialPatients);setConversations(initialConversations);},[initialAppointments,initialPatients,initialConversations]);
 useEffect(()=>{const s=createClient();const c=s.channel(`hospital-live-${hospitalId}`).on("postgres_changes",{event:"*",schema:"public",table:"messages"},p=>{if(p.eventType==="INSERT")setMessages(x=>[...x,p.new as Message])}).on("postgres_changes",{event:"*",schema:"public",table:"appointments",filter:`hospital_id=eq.${hospitalId}`},p=>{const r=p.new as Appointment;setAppointments(x=>p.eventType==="DELETE"?x.filter(i=>i.id!==p.old.id):[r,...x.filter(i=>i.id!==r.id)]);router.refresh();}).on("postgres_changes",{event:"*",schema:"public",table:"conversations",filter:`hospital_id=eq.${hospitalId}`},p=>{const r=p.new as Conversation;if(p.eventType!=="DELETE")setConversations(x=>[r,...x.filter(i=>i.id!==r.id)])}).subscribe();return()=>{s.removeChannel(c)}},[hospitalId,router]);
 async function signOut(){await createClient().auth.signOut();router.replace("/login");router.refresh()}
 async function appointmentAction(id:string,status?:string,remove?:boolean){const s=createClient(); if(remove){await s.from("appointments").delete().eq("id",id)}else await s.from("appointments").update({status}).eq("id",id); router.refresh();}
 async function clearChat(){if(!selectedConversation||!confirm(`Clear the chat history for ${selectedConversation.phone_number}? The patient can then begin a new booking conversation.`))return;const s=createClient();const [{error:draftError},{error:messageError}]=await Promise.all([s.from("appointment_drafts").delete().eq("conversation_id",selectedConversation.id),s.from("messages").delete().eq("conversation_id",selectedConversation.id)]);if(draftError||messageError){alert("Unable to clear this chat. Please try again.");return;}setMessages(items=>items.filter(item=>item.conversation_id!==selectedConversation.id));router.refresh();}
 async function addDoctor(){const name=prompt("Doctor name"); const department=prompt("Department"); if(!name||!department)return; const {data}=await createClient().from("doctors").insert({hospital_id:hospitalId,name,department}).select().single();if(data)setDoctors(x=>[...x,data as Doctor]);}
 async function toggleDoctor(doctor:Doctor){const {data}=await createClient().from("doctors").update({enabled:!doctor.enabled}).eq("id",doctor.id).select().single();if(data)setDoctors(x=>x.map(d=>d.id===doctor.id?data as Doctor:d));}
 async function editDoctor(doctor:Doctor){const department=prompt('Department',doctor.department);const duration=prompt('Consultation duration (minutes)',String(doctor.consultation_duration));if(!department||!duration)return;const {data}=await createClient().from('doctors').update({department,consultation_duration:Number(duration)}).eq('id',doctor.id).select().single();if(data)setDoctors(x=>x.map(d=>d.id===doctor.id?data as Doctor:d));}
 async function saveSettings(){if(!settings)return;const {data}=await createClient().from('hospital_settings').upsert({...settings,hospital_id:hospitalId}).select().single();if(data)setSettings(data as HospitalSettings);}
 const cards=[['Today\'s Appointments',active.filter(x=>x.appointment_date===today).length],['Upcoming Appointments',active.length],['Completed',appointments.filter(x=>x.status==='completed').length],['Cancelled',appointments.filter(x=>x.status==='cancelled').length],['Total Patients',patients.length]];
 const appointmentTable=<div className="table-wrap"><table><thead><tr>{['Patient','Phone Number','Doctor','Department','Date','Time','Checkup status','Actions'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{appointments.map(a=><tr key={a.id}><td>{a.patient_name}</td><td>{a.phone_number}</td><td>{a.doctor_name||'—'}</td><td>{a.department||'—'}</td><td>{a.appointment_date}</td><td>{time(a.appointment_time)}</td><td><span className={`badge ${a.status}`}>{a.status==='completed'?'Checkup complete':a.status==='upcoming'?'Checkup incomplete':a.status}</span></td><td className="actions"><button onClick={()=>alert(JSON.stringify(a,null,2))}>View</button><button onClick={()=>{const patient_name=prompt('Patient name',a.patient_name);if(patient_name)createClient().from('appointments').update({patient_name}).eq('id',a.id).then(()=>router.refresh())}}>Edit</button><button onClick={()=>{const date=prompt('New date (YYYY-MM-DD)',a.appointment_date);const slot=prompt('New time (HH:MM)',a.appointment_time.slice(0,5));if(date&&slot)createClient().from('appointments').update({appointment_date:date,appointment_time:slot}).eq('id',a.id).then(()=>router.refresh())}}>Reschedule</button>{a.status==='completed'?<button onClick={()=>appointmentAction(a.id,'upcoming')}>Mark incomplete</button>:<button onClick={()=>appointmentAction(a.id,'completed')}>Checkup complete</button>}<button onClick={()=>appointmentAction(a.id,'cancelled')}>Cancel</button><button onClick={()=>appointmentAction(a.id,undefined,true)}>Delete</button></td></tr>)}</tbody></table></div>;
 let content:React.ReactNode;
 if(view==='Dashboard')content=<><div className="page-title"><div><div className="eyebrow">ABC HOSPITAL</div><h1>Hospital Dashboard</h1><p>Appointment activity at a glance.</p></div></div><div className="stats">{cards.map(([label,value])=><article key={String(label)} className="stat"><span>{label}</span><strong>{value}</strong></article>)}</div><section className="panel"><h2>Today’s appointments</h2>{appointmentTable}</section></>;
 else if(view==='Appointments')content=<><div className="page-title"><div><div className="eyebrow">SCHEDULING</div><h1>Appointments</h1></div></div>{appointmentTable}</>;
 else if(view==='Doctors')content=<><div className="page-title"><div><div className="eyebrow">CLINICAL TEAM</div><h1>Doctors</h1></div><button className="primary small" onClick={addDoctor}>+ Add doctor</button></div><div className="doctor-grid">{doctors.map(d=><article className="doctor-card" key={d.id}><span className="avatar">{d.name.slice(0,1)}</span><h2>{d.name}</h2><p>{d.department}</p><small>{d.working_days.join(', ')} · {time(d.start_time)}–{time(d.end_time)} · {d.consultation_duration} min</small><button onClick={()=>editDoctor(d)}>Edit</button><button onClick={()=>toggleDoctor(d)}>{d.enabled?'Disable':'Enable'}</button><button onClick={()=>{if(confirm(`Delete ${d.name}?`))createClient().from('doctors').delete().eq('id',d.id).then(()=>setDoctors(x=>x.filter(i=>i.id!==d.id)))}}>Delete</button></article>)}</div></>;
 else if(view==='Patients')content=<><div className="page-title"><div><div className="eyebrow">PATIENT DIRECTORY</div><h1>Patients</h1></div></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Phone Number</th><th>Last Seen</th></tr></thead><tbody>{patients.map(p=><tr key={p.id}><td>{p.full_name||'—'}</td><td>{p.phone_number}</td><td>{new Date(p.last_seen).toLocaleString()}</td></tr>)}</tbody></table></div></>;
 else if(view==='WhatsApp Chats')content=<><div className="chat-page"><aside className="chat-list"><input placeholder="Search conversations" value={query} onChange={e=>setQuery(e.target.value)}/>{conversations.filter(c=>c.phone_number.includes(query)).map(c=><button className={c.id===selected?'selected':''} onClick={()=>setSelected(c.id)} key={c.id}><b>{patients.find(p=>p.phone_number===c.phone_number)?.full_name||'Patient'}</b><small>{c.phone_number}</small></button>)}</aside><section className="whatsapp-thread">{selectedConversation?<><header><div><b>{patients.find(p=>p.phone_number===selectedConversation.phone_number)?.full_name||'Patient'}</b><small>{selectedConversation.phone_number} · Last seen {new Date(selectedConversation.updated_at).toLocaleString()}</small></div><div className="chat-actions"><span className="badge upcoming">WhatsApp</span><button onClick={clearChat}>Clear chat</button></div></header><main>{thread.length?thread.map(m=><div className={`bubble ${m.role}`} key={m.id}>{m.content}</div>):<div className="empty">Chat cleared. The patient&apos;s next message will start a new booking.</div>}</main></>:<div className="empty">Choose a patient conversation</div>}</section></div></>;
 else if(view==='Calendar')content=<><div className="page-title"><div><div className="eyebrow">CALENDAR</div><h1>Upcoming schedule</h1></div></div><div className="calendar-list">{active.map(a=><article key={a.id}><b>{a.appointment_date} · {time(a.appointment_time)}</b><span>{a.patient_name} with {a.doctor_name||a.department}</span></article>)}</div></>;
 else if(view==='WhatsApp Connection')content=<><div className="page-title"><div><div className="eyebrow">WHATSAPP PROVIDER</div><h1>Evolution API connection</h1><p>Connect this hospital&apos;s WhatsApp account and manage QR pairing.</p></div></div><section className="panel"><a className="primary small" href="/whatsapp">Open WhatsApp connection</a></section></>;
 else content=<><div className="page-title"><div><div className="eyebrow">ADMINISTRATION</div><h1>Hospital Settings</h1></div></div>{settings&&<section className="panel settings"><label>Hospital name<input value={settings.hospital_name} onChange={e=>setSettings({...settings,hospital_name:e.target.value})}/></label><label>Departments (comma separated)<input value={settings.departments.join(', ')} onChange={e=>setSettings({...settings,departments:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></label><label>Opening time<input type="time" value={settings.opening_time.slice(0,5)} onChange={e=>setSettings({...settings,opening_time:e.target.value})}/></label><label>Closing time<input type="time" value={settings.closing_time.slice(0,5)} onChange={e=>setSettings({...settings,closing_time:e.target.value})}/></label><label>Slot duration (minutes)<input type="number" value={settings.slot_duration} onChange={e=>setSettings({...settings,slot_duration:Number(e.target.value)})}/></label><label>Emergency number<input value={settings.emergency_number||''} onChange={e=>setSettings({...settings,emergency_number:e.target.value})}/></label><label>WhatsApp number<input value={settings.whatsapp_number||''} onChange={e=>setSettings({...settings,whatsapp_number:e.target.value})}/></label><button className="primary small" onClick={saveSettings}>Save settings</button></section>}</>;
 return <main className="hospital" data-theme={dark?'dark':'light'}><aside className="main-nav"><div className="hospital-brand"><span>✚</span><b>{settings?.hospital_name||'ABC Hospital'}</b><small>Appointment assistant</small></div>{nav.map(n=><button key={n} onClick={()=>setView(n)} className={view===n?'active':''}>{n}</button>)}<button onClick={()=>setDark(x=>!x)}>{dark?'☀ Light mode':'◐ Dark mode'}</button><button className="signout" onClick={signOut}>Sign out</button></aside><section className="content">{content}</section></main>;
}
