"use client";
import { useEffect, useState } from "react";

type Connection = { server_url: string; instance_name: string; status: "connected" | "disconnected" | "connecting" | "qr_pending"; qr_code: string | null; last_error: string | null; updated_at: string };
const statusText = { connected: "Connected", disconnected: "Disconnected", connecting: "Connecting", qr_pending: "QR Pending" };

export default function WhatsAppConnection() {
  const [connection, setConnection] = useState<Connection | null>(null);
  const [webhookUrl, setWebhookUrl] = useState("");
  const [serverUrl, setServerUrl] = useState(""); const [apiKey, setApiKey] = useState(""); const [instanceName, setInstanceName] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function refresh() { const res = await fetch("/api/evolution/connection"); if (res.ok) { const body = await res.json(); setConnection(body.connection); if (body.connection) { setServerUrl(body.connection.server_url); setInstanceName(body.connection.instance_name); } } }
  useEffect(() => { refresh(); const timer = setInterval(refresh, 10000); return () => clearInterval(timer); }, []);
  async function connect(event: React.FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); setWebhookUrl(""); const res = await fetch("/api/evolution/connection", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ serverUrl, apiKey, instanceName, action: connection ? "reconnect" : "connect" }) }); const body = await res.json(); setBusy(false); if (!res.ok) { setMessage(body.error ?? "Connection failed."); return; } setConnection((current) => ({ ...(current ?? { server_url: serverUrl, instance_name: instanceName, last_error: null, updated_at: new Date().toISOString() }), status: body.status, qr_code: body.qrCode })); setWebhookUrl(body.webhookUrl ?? ""); setMessage("Connection settings refreshed. Use the signed URL below in Evolution Cloud."); }
  return <main className="shell"><section className="connection-card"><div className="brand">Hospital WhatsApp</div><h1>Connect Evolution API</h1><p>Connect this hospital&apos;s own WhatsApp account. Credentials are encrypted before storage.</p>{connection && <div className={`connection-status ${connection.status}`}><b>{statusText[connection.status]}</b><span>{connection.instance_name}</span></div>}<form onSubmit={connect}><label className="field">Evolution API server URL<input required placeholder="https://your-evolution-server.com" value={serverUrl} onChange={(e) => setServerUrl(e.target.value)} /></label><p className="field-help">Paste the API root only: <code>https://your-domain.cloud-station.app</code>. Do not paste the <code>/manager</code> page.</p><label className="field">Evolution API key<input required type="password" placeholder={connection ? "Enter key to reconnect" : "API key"} value={apiKey} onChange={(e) => setApiKey(e.target.value)} /></label><label className="field">Instance name<input required placeholder="abc-hospital" value={instanceName} onChange={(e) => setInstanceName(e.target.value)} /></label>{message && <p className="error">{message}</p>}<button className="primary" disabled={busy}>{busy ? "Connecting…" : connection ? "Refresh webhook URL" : "Connect WhatsApp"}</button></form>{webhookUrl && <section className="qr"><h2>Evolution Cloud webhook URL</h2><p>Copy this exact URL into Evolution Manager → Events → Webhook. Keep Webhook by Events off.</p><code className="webhook-url">{webhookUrl}</code></section>}{connection?.qr_code && connection.status !== "connected" && <section className="qr"><h2>Scan this QR code</h2><img src={connection.qr_code} alt="Evolution API WhatsApp QR code" /><p>WhatsApp → Settings → Linked devices → Link a device.</p></section>}<a className="back-link" href="/dashboard">← Back to hospital dashboard</a></section></main>;
}
