"use client";
import { useEffect, useState } from "react";

type Connection = { phone_number_id: string; display_phone_number: string | null; status: "connected" | "disconnected"; last_error: string | null; updated_at: string };

export default function WhatsAppConnection() {
  const [connection, setConnection] = useState<Connection | null>(null);
  const [phoneNumberId, setPhoneNumberId] = useState(""); const [accessToken, setAccessToken] = useState(""); const [verifyToken, setVerifyToken] = useState(""); const [displayPhoneNumber, setDisplayPhoneNumber] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function refresh() { const response = await fetch("/api/meta/connection"); if (response.ok) { const body = await response.json(); setConnection(body.connection); if (body.connection) { setPhoneNumberId(body.connection.phone_number_id); setDisplayPhoneNumber(body.connection.display_phone_number ?? ""); } } }
  useEffect(() => { refresh(); }, []);
  async function save(event: React.FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); const response = await fetch("/api/meta/connection", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ phoneNumberId, accessToken, verifyToken, displayPhoneNumber }) }); const body = await response.json(); setBusy(false); if (!response.ok) { setMessage(body.error ?? "Unable to save Meta connection."); return; } setAccessToken(""); setVerifyToken(""); setMessage("Saved. Complete webhook verification in Meta using the instructions below."); await refresh(); }
  const webhook = typeof window === "undefined" ? "/api/webhook" : `${window.location.origin}/api/webhook`;
  return <main className="shell"><section className="connection-card"><div className="brand">Hospital WhatsApp</div><h1>Connect Meta WhatsApp Business</h1><p>Use the official WhatsApp Cloud API. Your access token is encrypted before storage.</p>{connection && <div className={`connection-status ${connection.status}`}><b>{connection.status === "connected" ? "Connected" : "Disconnected"}</b><span>{connection.display_phone_number || connection.phone_number_id}</span></div>}<form onSubmit={save}><label className="field">WhatsApp Phone Number ID<input required inputMode="numeric" value={phoneNumberId} onChange={(event) => setPhoneNumberId(event.target.value)} placeholder="From Meta WhatsApp API setup" /></label><label className="field">Permanent access token<input required type="password" value={accessToken} onChange={(event) => setAccessToken(event.target.value)} placeholder={connection ? "Enter a new token to update" : "Meta permanent access token"} /></label><label className="field">Webhook verify token<input required type="password" value={verifyToken} onChange={(event) => setVerifyToken(event.target.value)} placeholder="Create your own secret token" /></label><label className="field">Display phone number (optional)<input value={displayPhoneNumber} onChange={(event) => setDisplayPhoneNumber(event.target.value)} placeholder="For example +91 94208 57650" /></label>{message && <p className="error">{message}</p>}<button className="primary" disabled={busy}>{busy ? "Saving…" : "Save Meta connection"}</button></form><section className="qr"><h2>Meta webhook setup</h2><ol><li>In <b>Meta for Developers</b>, create or select a Business app and add the <b>WhatsApp</b> product.</li><li>Open WhatsApp → Configuration and paste this Callback URL:</li></ol><code className="webhook-url">{webhook}</code><ol start={3}><li>Paste the same verify token entered above in Meta&apos;s Verify token field.</li><li>Click <b>Verify and save</b>, then subscribe to the <b>messages</b> webhook field.</li><li>Generate a permanent system-user token with <code>whatsapp_business_messaging</code> and <code>whatsapp_business_management</code>, then paste it above.</li></ol></section><a className="back-link" href="/dashboard">← Back to hospital dashboard</a></section></main>;
}
